name: maven
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [24]
        # and run on both Linux and Windows
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v4.7.1
          with:
              java-version: ${{ matrix.java }}
              distribution: zulu
        - name: Build with Maven
          run: mvn clean install
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          if: ${{ matrix.java == 24 && matrix.os == 'ubuntu-latest' }}
          with:
            name: standalone-jar
            path: target/ArrayV-*.jar
